# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gmagick"
    loaders:
        default:
            filesystem:
                locator: filesystem
                data_root:
                    - /app/assets/

    # configure resolvers
    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path: ~
#                web_root: /app/public/

    filter_sets:
        cache: ~

        col4:
            format: webp
            quality: 80
            filters:
                thumbnail: { size: [ 408, 272 ], mode: inset }

        fullwidth:
            format: webp
            quality: 80
            filters:
                thumbnail: { size: [ 730, 487 ], mode: inset }

        fullwidth_fallback:
            format: jpg
            quality: 70
            filters:
                thumbnail: { size: [ 730, 487 ], mode: inset }

# pas utile dans notre contexte.
    twig:
        assets_version: 5