services:
  nginx:
    depends_on:
      php:
        condition: service_started
    # voir config dans docker/nginx_prod.conf
    expose:
      - "90"
    image: nginx:1.26.0
    networks:
      nginx: null
    ports:
      - target: 90
        published: "${NGINX_PORT}"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./docker/nginx_dev.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./public
        target: /app/public
  php:
    image: ghcr.io/sebsept/docker-php-symfony-starter:dev
    networks:
      - nginx
      - partage
    restart: unless-stopped
    #    user: www-data
    # user est défini dans le Dockerfile à www-data
    # pour que les commandes composer et console tourne avec le bon user (php-fpm)
    # pour continuer à modifier les fichiers avec l'utilisateur courant
    # sudo chown seb:82 -R .
    # sudo chmod g+w -R .
    # de cette façon, les fichiers appartiennent à seb et au groupe www-data
    # on peut les créer/modifier des 2 cotés
    volumes:
      - type: bind
        source: ./
        target: /app
networks:
  nginx:
  partage:
    external: true

